name: Trigger auto deployment for myvault-container-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/myvault-container-api-AutoDeployTrigger-3d47999e-b64a-48a8-9c51-688d9d42f819.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MYVAULTCONTAINERAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYVAULTCONTAINERAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYVAULTCONTAINERAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: myvaultapiacr-a9cyfhdkakd3gwb7.azurecr.io
          registryUsername: ${{ secrets.MYVAULTCONTAINERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYVAULTCONTAINERAPI_REGISTRY_PASSWORD }}
          containerAppName: myvault-container-api
          resourceGroup: myvalut-rg
          imageToBuild: myvaultapiacr-a9cyfhdkakd3gwb7.azurecr.io/myvault-container-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


